### ISSUE TITLE
Propagate the logical call context between steps

### ISSUE THREAD

**Issue by thomaslevesque** [adamralph/xbehave.net#286] opened 2016-01-11 22:36 UTC
As discussed in FakeItEasy/FakeItEasy#575.

This scenario fails:

``` c#
public class LogicalCallContextSpecs
{
    [Scenario]
    public void PropagatingLogicalCallContext()
    {
        "when a step sets a value in the logical call context"
            .x(() => CallContext.LogicalSetData("mydata", "foobar"));

        "then the following step should be able to read the value from the logical call context"
            .x(() => CallContext.LogicalGetData("mydata").Should().Be("foobar"));
    }
}
```

I think the call context should be propagated between steps, otherwise there are many real-world scenarios (e.g. any scenario with thread or task affinity) that can't be tested with xBehave.

I copied my analysis from the PR mentioned above:

> Apparently, xBehave is executing each step in a threadpool thread. So any change to the call context that is done in a step isn't propagated to the subsequent steps... I think it would need to capture the `ExecutionContext` after each step, and pass it to the next step with `ExecutionContext.Run`. I did a quick POC in LinqPad and it seems to work:
> 
> https://gist.github.com/thomaslevesque/8a43ef3f0db3bd6061dd

**Comment by adamralph** [comment] 2016-01-26 18:10
I agree that all the steps in a scenario should execute under the same context. The main challenge is going to be to figure out how to properly weave this into [the magic of the step body invocation](https://github.com/xbehave/xbehave.net/blob/7c49a81af810ee7a9902ffea6008ed7a046d1f2a/src/Xbehave.2.Execution.desktop/StepInvoker.cs#L60-L90).

**Comment by adamralph** [comment] 2016-01-26 18:12
For my own reference - http://blogs.msdn.com/b/pfxteam/archive/2012/06/15/executioncontext-vs-synchronizationcontext.aspx

**Comment by adamralph** [comment] 2016-02-10 08:16
I'm having absolutely no luck getting this to work :confounded: 

I've written a [failing test](https://github.com/adamralph/xbehave.net/commit/3adb1ee0c9044b76bbd7f0b1ef25cffb28fec7ba) and made a [feeble attempt](https://github.com/adamralph/xbehave.net/commit/538e43fdcc28f6b7e3db10a4fa8aaef518aba11d) at making it green but I keep hitting walls/going round in circles.

Help me async experts... 

![image](http://45.media.tumblr.com/tumblr_lkot6w6QHJ1qcrzkko1_500.gif)

You're my only hope...

/cc @JakeGinnivan @danielmarbach @bradwilson

**Comment by danielmarbach** [comment] 2016-02-10 08:42
welcome to [danger of thread local land](http://particular.net/blog/the-dangers-of-threadlocal)

**Comment by adamralph** [comment] 2016-02-10 08:45
@danielmarbach the problem isn't thread local.

Thread local is only used in xbehave when registering the steps, and for this reason, xbehave scenarios themselves must not be written as async methods (I'm planning a Roslyn analyzer to warn against this). The steps themselves however, can be async (and in fact sync steps are wrapped as async) and during invocation there is no use of thread local.

**Comment by danielmarbach** [comment] 2016-02-10 08:50
You don't understand my point (and I failed to express it). My point is not `ThreadLocal` as a usage. It is about data ambient to the current Thread. With async that changes completely. In short:

CallContext can't be properly used with async code. Microsoft itself has recommended against using CallContext for anything except remoting (the corresponding connect link is down unfortunately). The call context has no knowledge of early returns and resumes of async continuations

**Comment by danielmarbach** [comment] 2016-02-10 08:51
The only work around I see currently is to introduce a logical call context like highlighted in my blog post I linked above. here is the direct link 

http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html

**Comment by danielmarbach** [comment] 2016-02-10 08:54
Since xunit 2 moves to an async model internally and you as well in xbehave major I'd say close as won't fix because CallContext is not intended to be used under async code. Any trickery you apply might hunt you down in unforeseen ways

**Comment by danielmarbach** [comment] 2016-02-10 08:58
Sorry I misread the code example above. @thomaslevesque is already using

LogicalSetData/LogicalGetData 

https://visualstudio.uservoice.com/forums/121579-visual-studio-2015/suggestions/2698599-add-an-async-compatible-logical-call-context

and they work with .NET 4.5 in combination with async/await. The statements I made above are only true for prio .NET 4.5 behavior.

**Comment by adamralph** [comment] 2016-02-10 09:01
Yep, xbehave 2.0 is .NET 4.5 only.

**Comment by thomaslevesque** [comment] 2016-02-10 09:05
I had a few ideas about how to do this; I'll try to take a closer look later today.

**Comment by danielmarbach** [comment] 2016-02-10 10:06
![image](https://cloud.githubusercontent.com/assets/174258/12944284/62cd21ac-cfe6-11e5-94a6-552dd7b2dd12.png)

**Comment by adamralph** [comment] 2016-02-10 10:21
Wow! With no changes?

**Comment by danielmarbach** [comment] 2016-02-10 10:25
Made a few changes. But now comes the quiz question:

What should the behavior be with:

```
    [Scenario]
    public void UsingLogicalDataWithAsync(object data)
    {
        "Given I have set some logical data"
            .f(async () =>
            {
                await Task.Yield();
                CallContext.LogicalSetData("foo", "bar");
                await Task.Yield();
            });

        "When I get the logical data"
            .f(async () =>
            {
                await Task.Yield();
                data = CallContext.LogicalGetData("foo");
                await Task.Yield();
            });

        "Then the logical data should be that which was set"
            .f(() => ((string)data).Should().Be("bar"));
    } 
```

**Comment by adamralph** [comment] 2016-02-10 10:40
In my naivety, I would say it should also work.

How do the yields change things?

**Comment by danielmarbach** [comment] 2016-02-10 10:42
Here is the ugly approach which works with sync delegates. Executing the body in an async void delegate is kinda ugly but should work since we have the surrounding context which intercepts the delegates and pumps them

https://github.com/danielmarbach/xbehave.net/tree/286-logical-call-context-ex

**Comment by danielmarbach** [comment] 2016-02-10 10:43
The scenario described in https://github.com/xbehave/xbehave.net/issues/286#issuecomment-182297575 doesn't work

**Comment by adamralph** [comment] 2016-02-10 11:33
Wow, nice work!

For some reason I couldn't reconcile myself with the
`ExecutionContext.Run()` signature and the need to execute the async body.
I never thought of executing the body as `async void` but, as you say, that
works due to the custom sync context from xunit. I also didn't realise I
could pass a null context initially.

It's a shame it doesn't work for async steps but, as @damianh is
suggesting, I'm beginning to think this whole thing may be a can of worms
which is best avoided.

**Comment by danielmarbach** [comment] 2016-02-10 11:51
Yes it is a can of worms

> Am 10.02.2016 um 12:33 schrieb Adam Ralph notifications@github.com:
> 
> Wow, nice work!
> 
> For some reason I couldn't reconcile myself with the
> `ExecutionContext.Run()` signature and the need to execute the async body.
> I never thought of executing the body as `async void` but, as you say, that
> works due to the custom sync context from xunit. I also didn't realise I
> could pass a null context initially.
> 
> It's a shame it doesn't work for async steps but, as @damianh is
> suggesting, I'm beginning to think this whole thing may be a can of worms
> which is best avoided.

**Comment by bradwilson** [comment] 2016-02-10 19:54
Just to verify: `CallContext.LogicalGetData` and `CallContext.LogicalSetData` are the correct way to do this on .NET 4.5.

.NET 4.6 ships with an `AsyncLocal<T>` that is implemented in terms of internal stuff, so looking at its internal implementation isn't necessarily helpful. If you look at [Microsoft.VisualStudio.Threading](https://www.nuget.org/packages/Microsoft.VisualStudio.Threading/), you'll see that the `AsyncLocal<T>` inside VS 2015 for .NET 4.5 is implemented in terms of `CallContext`:

``` csharp
public override T Value
{
    get
    {
        object obj = CallContext.LogicalGetData(this.callContextKey);
        if (obj != null)
        {
            object obj2 = this.syncObject;
            lock (obj2)
            {
                T result;
                if (this.valueTable.TryGetValue(obj, out result))
                {
                    return result;
                }
            }
        }
        return default(T);
    }
    set
    {
        if (value != null)
        {
            object obj = this.syncObject;
            lock (obj)
            {
                object obj2;
                if (!this.reverseLookupTable.TryGetValue(value, out obj2))
                {
                    obj2 = new AsyncLocal<T>.AsyncLocalCallContext.IdentityNode();
                    this.reverseLookupTable.Add(value, obj2);
                }
                CallContext.LogicalSetData(this.callContextKey, obj2);
                this.valueTable.Remove(obj2);
                this.valueTable.Add(obj2, value);
                return;
            }
        }
        CallContext.FreeNamedDataSlot(this.callContextKey);
    }
}
```

Their implementation seems a little unnecessarily complex (I'd love to know what motivated it). We wrote one for a "private" fork of NSubstitute when we discovered that it was using a Task-unfriendly thread local. Our implementation is quite a bit simpler:

https://github.com/CenturyLinkCloud/NSubstitute/blob/master/Source/NSubstitute/Core/RobustThreadLocal_Net45.cs

**Comment by adamralph** [comment] 2016-02-10 20:06
@bradwilson thanks for chiming in. That's interesting. I can only guess that setting the NSub `SubstitutionContext` in your forked package won't propagate across xbehave steps either.

This issue was driven by [a proposal to use logical call context inside FakeItEasy](https://github.com/FakeItEasy/FakeItEasy/pull/575) in, effectively, the same way as you did in your branch of NSub. My current stance is that it's probably a bad thing for a mocking framework to assume that all test frameworks will flow the context correctly so I'm getting cold feet about adding it to FIE and tipping towards closing this as a won't fix in xbehave.

**Comment by thomaslevesque** [comment] 2016-02-10 20:36
> What should the behavior be with:

Ideally, it should also work, but I don't think it's possible to make it work. If the steps are async, the copy-on-write behavior of the logical context is used, which means that any change made in a step after an `await` will never be visible to the caller (changes made _before_ the await will be visible)... As much as I'd like this to be fixed, I think it's a dead end.

**Comment by bradwilson** [comment] 2016-02-10 23:48
> My current stance is that it's probably a bad thing for a mocking framework to assume that all test frameworks will flow the context correctly

You're worried for naught, IMO.

Flowing execution context is something you only need to do when you're writing your own by-hand custom synchronization context with custom worker threads, like we did for [max concurrency](https://github.com/xunit/xunit/blob/10ac1bc821b28f9cc310a9c448f173760f9b05d6/src/xunit.execution/Sdk/MaxConcurrencySyncContext.cs). AFAIK, we're the only ones who've ever done that. The built-in sync contexts (which many people end up using as base classes) already do this for you.

**Comment by adamralph** [comment] 2016-02-16 06:53
@bradwilson the problem is that it currently doesn't work in xbehave so I must have to do _something_ to make it work.

I'm using the `AsyncTestContext` from xunit to [invoke the step bodies](https://github.com/xbehave/xbehave.net/blob/7c49a81af810ee7a9902ffea6008ed7a046d1f2a/src/Xbehave.2.Execution.desktop/StepInvoker.cs#L65-L86) so, as you suggest, I would have expected it to Just Work™, but for some reason it doesn't, and for that reason I'm finding myself delving in and having to manipulate the `ExecutionContext` etc., and this is where I'm getting lost. It doesn't seem to behave in the way my limited expertise suggests it should.

I'd love to find a way to flow the context correctly between the steps but I feel like I'm at a dead end.

**Comment by i3arnon** [comment] 2016-02-16 07:26
@adamralph what's wrong with what @danielmarbach suggested?

It's true that it if the steps themselves call async methods the changes they make to the `LogicalCallContext` won't affect the next steps but that's the case for all async methods because of the copy-on-write semantics of the `LogicalCallContext`.

This async case wouldn't work with xbehave but it wouldn't work with anything else either as the limit is in the framework.

**Comment by adamralph** [comment] 2016-02-16 07:34
@i3arnon my knowledge of how this is all supposed to work is probably the limiting factor here.

I must be missing something. Is it true that the following won't work because of copy-on-write?

``` C#
[Fact]
public async Task UsingLogicalDataWithAsync()
{
    await Task.Yield();
    CallContext.LogicalSetData("foo", "bar");
    await Task.Yield();

    await Task.Yield();
    var data = CallContext.LogicalGetData("foo");
    await Task.Yield();

    ((string)data).Should().Be("bar"));
}
```

**Comment by i3arnon** [comment] 2016-02-16 08:01
@adamralph No, it would, as the copy-on-write behaviour is relevant when calling other async methods.

This, however, won't work:

```
[Fact]
public async Task UsingLogicalDataWithAsync()
{
    await SetAsync();
    await GetAsync();
}

async Task SetAsync()
{
    await Task.Yield();
    CallContext.LogicalSetData("foo", "bar");
    await Task.Yield();
}

async Task GetAsync()
{
    await Task.Yield();
    var data = CallContext.LogicalGetData("foo");
    await Task.Yield();

    ((string)data).Should().Be("bar"));
}
```

Which I guess is more similar to running each step separately.

**Comment by bradwilson** [comment] 2016-02-16 08:06
@adamralph wrote:

> Is it true that the following won't work because of copy-on-write?

The copy-on-write behavior comes from the FSM that's built by the compiler for async methods. The intent is that changes inside an async method would not leak back out into the caller. In the example you give, all of those calls to CallContext are using the same CallContext because they're in the same method.

This should fail, because of the copy-on-write behavior:

``` csharp
[Fact]
public async Task TheTest()
{
    CallContext.LogicalSetData("foo", "bar");
    await HelperMethod();
    var data = CallContext.LogicalGetData("foo");
    ((string)data).Should().Be("baz");
}

async Task HelperMethod()
{
    CallContext.LogicalSetData("foo", "baz");
    await Task.Yield();
}
```

Fails with:

```
Assert.Equal() Failure
            ↓ (pos 2)
Expected: baz
Actual:   bar
            ↑ (pos 2)
```

**Comment by adamralph** [comment] 2016-02-16 08:35
@i3arnon @bradwilson thanks for the explanations, I believe I understand the behaviour now.

It's becoming clear that the concept of xbehave steps is at odds with the behaviour of the logical call context. With xbehave steps, the intended abstraction is that the steps are, effectively, "labelled parts" of a single logical method, rather than independent methods.

This means that this xbehave scenario:

``` C#
[Scenario]
public void UsingLogicalDataWithAsync(object data)
{
    "Given I have set some logical data"
        .f(async () =>
        {
            await Task.Yield();
            CallContext.LogicalSetData("foo", "bar");
            await Task.Yield();
        });

    "When I get the logical data"
        .f(async () =>
        {
            await Task.Yield();
            data = CallContext.LogicalGetData("foo");
            await Task.Yield();
        });

    "Then the logical data should be that which was set"
        .f(() => ((string)data).Should().Be("bar"));
}
```

is expected to behave identically to this xunit fact:

``` C#
[Fact]
public async Task UsingLogicalDataWithAsync()
{
    await Task.Yield();
    CallContext.LogicalSetData("foo", "bar");
    await Task.Yield();

    await Task.Yield();
    var data = CallContext.LogicalGetData("foo");
    await Task.Yield();

    ((string)data).Should().Be("bar"));
}
```

with the only difference being that, with the xbehave scenario, each "step" is reported independently as a success or failure in the test results.

The question that remains then, is whether it is possible to flow the context between the async steps in order to achieve that behaviour. If not, the "labelled method parts" abstraction of xbehave steps will, unfortunately, have a leak with respect to the logical call context, and libraries which use it for certain features, e.g. NSub or FIE, will break when that feature is used across xbehave steps. :cry:

**Comment by bradwilson** [comment] 2016-02-16 10:21
> It's becoming clear that the concept of xbehave steps is at odds with the behaviour of the logical call context.

Yes, I believe you're right. Each step there is an async method (lambda) with its own copy-on-write behavior. I'm pretty sure there's nothing you can do about that, because that behavior is being enforced by the compiler.

**Comment by thomaslevesque** [comment] 2016-02-16 13:03
I agree with @bradwilson here, I don't think it's possible to make it work for async steps. On the other hand, the `UsingLogicalDataWithAsync` example is very contrived, and real-world scenarios are unlikely to run into this problem (how often do you write an async step that makes changes to the logical context? me, never...).

So I think it's worth implementing the fix even if it supports "only" 99.9% of possible use cases.

**Comment by i3arnon** [comment] 2016-02-16 14:44
I think it's probably possible using internal methods in the framework.
The question is: do you want to go down this rabbit hole...?

**Comment by adamralph** [comment] 2016-02-16 16:33
@i3arnon no, not really :wink:

**Comment by adamralph** [comment] 2016-02-16 16:33
@thomaslevesque problems arise when some framework (e.g. FakeItEasy) [starts using logical call context internally](https://github.com/FakeItEasy/FakeItEasy/pull/575) without it being obvious to the test writer, e.g.

``` C#
[Scenario]
public void Fooing(IDep dep, Sut sut, IFakeScope scope)
{
    "Given a dep"
        .x(() => dep = A.Fake<IDep>());

    "And a SUT"
        .x(() => sut = new Sut(dep));

    "When I foo the SUT"
        .x(async c =>
        {
            scope = Fake.CreateScope().Using(c);
            await sut.FooAsync();
        });

    "Then the dep should have been barred"
        .x(c =>
        {
            scope.OrderedAssertions().Using(c);
            A.CallTo(() => fake.Bar()).MustHaveHappened();
        });

    "And then the dep should have been bazzed"
        .x(() => A.CallTo(() => fake.Baz()).MustHaveHappened());
}
```

This appears to be fine, but it isn't, because FakeItEasy is using logical call context internally in the call to `Fake.CreateScope()`, and that exists in an async step.

**Comment by thomaslevesque** [comment] 2016-02-16 16:48
> @thomaslevesque problems arise when some framework (e.g. FakeItEasy) starts using logical call context internally without it being obvious to the test writer, e.g.

True, but would you naturally write the scenario this way? It would be cleaner to create the scope in its own, non-async step (or perhaps not even in a step, because it's a purely technical artifact, which has nothing to do with the functional requirements)

**Comment by adamralph** [comment] 2016-02-16 16:56
@thomaslevesque to be fair, you probably wouldn't be using a mocking library with xbehave in most cases. xbehave is far more useful at a black box behavioural level, rather than a white box level where you inject fake objects into things.

Having said that, I have used it at testing levels with fakes involved before. You could do the entire set of assertions in a single step, but then you lose the benefit of an xbehave step identifying a specific assertion. It's not really possible to create the scope outside a step, because you woudn't be able to control it's disposal (the steps are registered when the scenario method is executed, but are themselves executed later).

**Comment by adamralph** [comment] 2016-02-16 16:57
Generally, nothing should really be done in an xbehave method outside the step bodies, it doesn't really make any sense to do so.

**Comment by adamralph** [comment] 2016-03-10 23:56
So, in summary, it appears that, thanks to @danielmarbach, we can solve this for [sync steps](https://github.com/xbehave/xbehave.net/issues/286#issuecomment-182307730), but not for [async steps](https://github.com/xbehave/xbehave.net/issues/286#issuecomment-184611668).

The question then is, is it worth supporting this just for sync steps? The solution looks fairly robust, but I'm loathed to add the complexity just for that case if it's not really going to solve anyone's problems. The only use case mentioned so far is [the proposal for FakeItEasy to use logical call context to solve async test problems](https://github.com/FakeItEasy/FakeItEasy/pull/575) but that solution has been abandoned in favour of a much simpler solution (the removal of static state).

I'm currently favouring closing this as a won't fix, until a real world case arises.

**Closed as completed** 2016-03-26 17:30 UTC
Labels: enhancement, wontfix
