### ISSUE TITLE
Testing in ASP.NET Core (.NET Framework 4.6.1)

### ISSUE THREAD

**Issue by Piotr1215** [adamralph/xbehave.net#366] opened 2017-01-25 15:13 UTC
Hi,

First, thanks for a great testing support. I enjoy using XBehave a lot :).

I'm in the process of writing a Web API in ASP.NET Core targeting .NET Framework 4.6.1. I would like to use XBehave, but given XBehave NuGet package, when I run the test, then instead of displaying steps names I only get name of the test in the Resharper test runner (the same is for VS Test runner), like so:

![image](https://cloud.githubusercontent.com/assets/8086638/22295861/a9baedba-e318-11e6-9a16-bc3e5dbdc400.png)

My project.json looks like this

![image](https://cloud.githubusercontent.com/assets/8086638/22296002/2f8374e4-e319-11e6-9aca-1431b6d3ed26.png)

Thanks in advance for your help

regards
Piotr

**Comment by adamralph** [comment] 2017-01-26 22:01
Hi @Piotr1215, thanks for raising this. Unfortunately, I don't think there's much that can be done about this.

The situation is a little complex, but I'll attempt to explain what's happening here.

When test runners such as Resharper "discover" xunit tests (including xbehave scenarios), they do so by scanning assemblies for the relevant attributes, e.g. `Fact`, `Theory` or `Scenario`. They then invoke "discovery" methods which provide "test cases" which are then displayed in the test runner UI.

For an xunit `Fact`, there is a single test case, which represents the invocation of the method marked as a `Fact`. For an xunit `Theory`, there is a test case for each dataset provided by an attribute such as `InlineData`. For an xbehave `Scenario`, there is a single test case representing the invocation of the scenario method, and that is what you see in the Resharper UI, as with `ScenarioName` in your example. 

Now, when the test case is executed, it may yield one or more "tests". A test case for an xunit `Fact` yields a single test and a test case for a specific dataset for an xunit `Theory` also yields a single test.

So you might ask, why have the concept of both test cases and tests? Well, in the case where the datasets for an xunit `Theory` cannot be serialised, only a single test case is yielded at discovery time, representing the theory method plus all the datasets provided to it. When the testcase is executed, a test is yielded for each dataset. In this case, you'd have a similar problem in the Resharper UI since you'd only see a single line in the UI representing the entire theory and all the datasets which are provided to it.

This is similar to what happens when an xbehave `Scenario` is executed. At discovery time, there is a single test case representing the scenario, but at runtime a separate test is yielded for each step within the scenario. This is the only way that xbehave scenarios can work, since they rely on the preservation of state between each step, and the execution of an individual step in isolation is illogical. E.g. if you could see all the steps within a scenario in your test runner as executable tests, what would you expect to happen if you only executed the last step in the scenario without executing the previous steps?

Now, it *may* be possible for test runners like Resharper to be enhanced to expand test cases at runtime and show the tests which are yielded at that time as distinct nodes underneath the node of the test case. Those sub-nodes would not be individually executable, only the test case node would be, because the *tests* are only known at runtime, and if the test code is edited, the number of tests could change from one test invocation to the next.

I hope I've got most of this correct. It would need people like @bradwilson to confirm whether my explanation of the workings of xunit is correct, and @citizenmatt to confirm whether I've correctly described the working of Resharper and whether my hypothesis about a possible enhancement there makes any sense.

BTW - the VS test runner exhibits the same problem.

**Comment by bradwilson** [comment] 2017-01-26 22:07
Spot on explanation.

There are other cases where a single test case yields multiple tests other than serialization issues: the user may select to disable pre-enumeration, the data attribute may choose to opt out (imagine feeding data from SQL, for example). The point that Adam is making is 100% right: there is always the possibility of a test case yielding multiple tests (and thus multiple test results). To the system, this is indivisible: test case is always the smallest runnable thing.

**Comment by citizenmatt** [comment] 2017-01-27 11:52
ReSharper already supports adding/removing nodes for theory test cases. It has to, in order to support theories that only enumerate at runtime (Brad's SQL based theories, for example).

However, individual nodes are individual, independent test cases, while the steps Adam's described are not - ReSharper will allow trying to run those steps individually (or even 3 out of 4 steps), which wouldn't work. We would have to change ReSharper to make those nodes non-executable. And IIRC, the child nodes are ordered alphabetically, rather than in the order they're discovered. We'd also need to decide what happens to the steps that aren't run - ReSharper would normally mark them as invalid and remove them.

**Comment by adamralph** [comment] 2017-01-27 18:31
@bradwilson thanks for the confirmation.

@Piotr1215 what this means is that xbehave is operating within the abstractions defined by xunit, so if test runners like ReSharper or the VS runner are not displaying something, e.g. multiple tests belonging to test cases, then we need to investigate those runners to find out why.

@citizenmatt thanks for chiming in.

> ReSharper already supports adding/removing nodes for theory test cases.

That's great to hear. In that case, can you explain what @Piotr1215 is seeing in his UI? I.e. just the test case (scenario name) and not the tests (steps)? Is he just using an older version which doesn't support this?

> We would have to change ReSharper to make those nodes non-executable.

In the case of xunit theories which only enumerate at runtime, assuming the data arguments are not serializable, how does ReSharper know how to invoke a specific test?

> the child nodes are ordered alphabetically

That works in favour of xbehave. The step display names are already specifically crafted so that an alphabetical (alphanumerical) sort results in the correct order.

**Comment by Piotr1215** [comment] 2017-01-27 22:29
@adamralph , @bradwilson , @citizenmatt thanks a lot for the detailed explanation on how the Xunit and Xbehave tests discovery and test cases execution work in unison with Resharper. 

> That's great to hear. In that case, can you explain what @Piotr1215 is seeing in his UI? I.e. just the test case (scenario name) and not the tests (steps)? Is he just using an older version which doesn't support this?

I think this is spot on explanation of the exact problem. Outside of .NET Core Xbehave behaves normally (pun intended ;)), meaning all the test steps are displayed correctly.

Just as a side note, I'm trying to find another solution to adopt Xunit to fit the Gherkin language and I ended up with a "Given..." class setting  up and tearing down the test fixtures for the resource under test and "When" classes for every HTTP Verb I'm using, for example "WhenGettingUsers". It does the job, but fluent naming that Xbehave provides nicely reduces the number of classes needed to accomplish the same task.

**Comment by adamralph** [comment] 2017-01-28 09:09
@Piotr1215 thanks for the info. I didn't realise that you only have this problem with .NET Core.

In that case, I'll rephrase my question to @citizenmatt: do you know why @Piotr1215 is seeing this difference between .NET Core and .NET FX? @bradwilson, are you aware of anything in xunit which could be provoking this difference in behaviour?

**Comment by adamralph** [comment] 2017-01-28 13:11
@Piotr1215 looking back at your snippets, it's look like you're not actually using .NET Core, you're using .NET Framework 4.6.1 (`net461`). When you say "Outside of .NET Core", what do exactly do you mean?

**Comment by citizenmatt** [comment] 2017-01-30 14:58
> In the case of xunit theories which only enumerate at runtime, assuming the data arguments are not serializable, how does ReSharper know how to invoke a specific test?

Tests are enumerated before executing, so it's possible to match and only execute the ones we're interested in. If we can't find them in the enumeration, ReSharper will clean them up from the tree view.

**Comment by citizenmatt** [comment] 2017-01-30 15:23
Also, just tested a simple xunit project (not xbehave) for .net core (CoreCLR + .NETFx) with theories and they work as expected, adding nodes under the test method.

**Comment by Piotr1215** [comment] 2017-02-02 08:39
Sorry for confusion, I should have been more precise. My project is ASP.NET Core targeting .NET Framework 4.6.1.

> When you say "Outside of .NET Core", what do exactly do you mean?

What I mean is that Xbehave works as expected in other project types that are not .NET Core (regardless of the target framework)

@citizenmatt this is correct, Xunit works perfectly fine with .NET Core targeting both netcoreapp or net461. The problem however remains with .NET Core app (in my case ASP.NET Core) and Xbehave.

**Comment by adamralph** [comment] 2017-02-04 10:58
@Piotr1215 I'm still quite confused regarding the platforms/frameworks involved. Would it be possible for you to publish a solution to GitHub with a minimal reproduction of the problem?

**Comment by adamralph** [comment] 2017-02-04 11:00
BTW - @citizenmatt thanks, that makes sense, and thanks for running those tests. I'll see what I can reproduce with xbehave on my end.

**Comment by Piotr1215** [comment] 2017-02-07 20:24
@adamralph sure. I have prepared two projects, one with exact same setup as I have for .NET Core and another one for "normal" .NET for comparison.

https://github.com/Piotr1215/CoreWithBehave

**Comment by adamralph** [comment] 2017-02-07 20:29
@Piotr1215 fantastic, thanks! I'll take a look ASAP.

**Comment by adamralph** [comment] 2017-02-09 18:29
@Piotr1215 I took a look at https://github.com/Piotr1215/CoreWithBehave but it doesn't contain the two projects shown in the README.md screenshot. It only has one project, CoreWithBehave, and that doesn't contain any tests. Did you forget to push some commits perhaps?

**Comment by Piotr1215** [comment] 2017-02-21 20:45
@adamralph sorry for the confusion, I didn't check in the projects indeed! Fixed now and also cloned the repo locally to be sure all is ok.

**Comment by adamralph** [comment] 2017-02-26 11:04
@Piotr1215 in my fork of your test repo, I've added [a regular xunit theory](https://github.com/adamralph/CoreWithBehave/blob/d045d8b05f8d4e38adcb5a6bab8dbeb806e556b2/CoreWithBehave.Specs/TestFeature.cs#L31-L46) (with parameters that do not serialise), and the behaviour is exactly the same as the xbehave scenario:

![image](https://cloud.githubusercontent.com/assets/677704/23339106/648e75ec-fc1b-11e6-8ae5-7072778e07cd.png)

@citizenmatt it seems this is indeed a general problem with xunit, Resharper, and project.json-based projects. Any idea where the problem lies? /cc @bradwilson

**Comment by citizenmatt** [comment] 2017-03-01 02:00
I'll take a look as soon as I can. But I'm at a conference this week, so it might take a couple of days.

**Comment by adamralph** [comment] 2017-05-21 08:13
@citizenmatt did you get a chance to look at this?

**Comment by citizenmatt** [comment] 2017-05-21 13:22
Ah, I'd forgotten about this, sorry. And now I'm confused as to what's going on again - can you summarise for me, please? :)

**Comment by iamkoch** [comment] 2017-05-30 13:35
To add onto this, it seems that if a single step fails which isn't the last step in the scenario, the test is marked as Ignored / Skipped as a result.

**Comment by adamralph** [comment] 2017-10-14 11:11
@iamkoch I'm guessing that's because ReSharper takes the result of the last step in the scenario and uses that as the result of the entire scenario.

@citizenmatt I've now had a chance to remind myself about this. The problem is that, when an xunit test case does not evaluate the tests at discovery time (more detail on that [here](https://github.com/xbehave/xbehave.net/issues/366#issuecomment-275527846)), ReSharper is treating all the tests as one single test. **This is not specific to xbehave**. You can reproduce this problem by running  [this xunit theory](https://github.com/adamralph/CoreWithBehave/blob/d045d8b05f8d4e38adcb5a6bab8dbeb806e556b2/CoreWithBehave.Specs/TestFeature.cs#L31-L46). As you can see from the screenshot [here](https://github.com/xbehave/xbehave.net/issues/366#issuecomment-282548264), when an xunit theory evaluates all the tests at discovery time, ReSharper shows them all as separate tests (first `MyTheory` in the screenshot). When an xunit theory evaluates the tests at execution time, ReSharper shows them all as a single test (second `MyTheory` in the screenshot).

**Comment by adamralph** [comment] 2017-10-14 11:26
This issue (referring to project.json) has been superseded by #373 which refers to SDK style projects.

**Closed as completed by adamralph** 2017-10-14 11:26 UTC
Labels: question
