### ISSUE TITLE
VS TestExplorer does not discover tests with XUnit 2.0 RC3 and xBehave 2.0 beta 4

### ISSUE THREAD

**Issue by huer12** [adamralph/xbehave.net#228] opened 2015-02-27 14:06 UTC
I tried to switch to the newest XUnit version 2.0 RC3, but in this version the VS TestExplorer does discover the scenarios anymore. Also the msbuild runner does not discover the scenarios.

Any suggestions?

**Comment by adamralph** [comment] 2015-02-28 14:54
Hi @huer12, when you say "switch to the newest XUnit version 2.0 RC3" what do you mean by that? Did you install the xunit.runners package into your project?

**Comment by huer12** [comment] 2015-03-01 10:24
Yes I installed the xunit runners for ms build and also the one for Visual
Studio.

2015-02-28 15:54 GMT+01:00 Adam Ralph notifications@github.com:

**Comment by adamralph** [comment] 2015-03-01 16:01
OK, thanks for reporting. I'll see if I can reproduce...

**Comment by adamralph** [comment] 2015-03-05 15:37
@huer12 I'm afraid I can't reproduce this. I installed xunit.runner.visualstudio 2.0.0-rc3-build1046 into a test project and the VS runner located the tests perfectly.

I've pushed the change to this branch if you want to see for yourself https://github.com/adamralph/scriptcs/tree/xunit-xbehave-vs-runner-test

**Comment by huer12** [comment] 2015-03-05 20:08
Hi Ralph

If you work with xunit 1.9.2 and Xbehave 1.1.0 it works, but if you work
with xunit 2.0.0 rc3 and Xbehave 2.0.0 beta 4 it does not. I have attached
a test program. It does find the test in the ClassLibrary1, but it does not
find the one in ConsoleApplication1.TestXBehave

Regards,
Roman

2015-03-05 16:37 GMT+01:00 Adam Ralph notifications@github.com:

**Comment by adamralph** [comment] 2015-03-05 20:14
Hi @huer12 yes, you're correct. Sorry, I didn't realise you were trying to use xBehave 2.0 beta. I'm actually in conversation with @bradwilson about this at the moment, since there are some issues surrounding the VS runner and extensions built over xunit 2.0. We're confident that they can be fixed with xunit 2.0 RC4. Once that has been released, I'll build and release xbehave 2.0 beta 5 which should fix this problem.

**Comment by huer12** [comment] 2015-03-05 21:07
Hi, thanks for the information. So I'm waiting.

2015-03-05 21:14 GMT+01:00 Adam Ralph notifications@github.com:

**Comment by adamralph** [comment] 2015-03-17 22:52
@huer12 this has been fixed in beta 6 (https://www.nuget.org/packages/Xbehave/2.0.0-beta006-build519)

For an example of it working, see https://github.com/xbehave/xbehave.net-samples

If you still run into problems with beta 6, feel free to reopen this issue.

**Closed as completed** 2015-03-17 22:52 UTC
Labels: question
